config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses, only: [:new,:create,:index,:show]
  resources :enrollments, only: [:index,:create]
  get '/register', to: 'enrollments#register'
  root to: 'courses#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    
        if user.is_admin?
          can :manage, :all
        else
          can :read, :all
        end
        
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :parent, class_name: "Course", optional: true
  has_many :children, class_name: "Course", foreign_key: :parent_id
  has_many :grandchildren, class_name: "Course", through: :children, source: :children
  has_many :greatgrandchildren, class_name: "Course", through: :children, source: :grandchildren

  has_many :enrollments
  has_many :users, through: :enrollments

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :enrollments, dependent: :destroy
  has_many :courses, through: :enrollments


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => "Not authorized!" }
    end
  end

  protected
  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password,:password_confirmation)}
    # devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname,/ :email, :password, :current_password)}
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.includes(:children).where("parent_id is NULL")
  end

  def new
    authorize! :new, @course
    @course = Course.new
    @categories = Course.all
  end

  def create
    course = Course.new(course_params)
    # Course.create!(course_params)
    if course.save!
        redirect_to courses_path, notice: 'Created Successfully'
    else 
      redirect_to new_course_path, alert: 'Unable to create course'
    end    
  end

  def show
    @category_courses = Course.includes(:children).where(parent_id: params[:id])
  end
 
  private
  def course_params
    params.require(:course).permit(:name, :parent_id, :description)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  
  def index
    @user_courses = current_user.courses
  end

  def create
    if Enrollment.exists?(user_id: current_user.id,course_id: params[:course_id])
      redirect_to courses_path, alert: 'Already Enrolled!'
    else
      @enrollment = Enrollment.create!(user_id: current_user.id,course_id: params[:course_id])
      redirect_to courses_path, notice: 'Enrolled Successfully'
    end  
  end

  def register
    @course = Course.find(params[:course_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/courses/index.html.erb
<div class='container-fluid mt-4 courses'>
  <% if !@courses.blank? %>
    <% @courses.each do |course| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= course.name %></h5>
        <p class="card-text"><%= course.description%></p>
        <%= link_to 'Available Courses', course, class: 'btn btn-outline-primary my-2 my-sm-0' %>
      </div>
    </div>
    <% end %>
  <% else %>
    <p>No Courses Available.</p>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="container-fluid w-25 mt-5">
  <form action="/courses" method='post'>
    <div class="form-group">
      <input type="text" class="form-control" id="course_name" name=course[name] aria-describedby="emailHelp" placeholder="Enter Course">
      <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">
    </div>
    <div class="form-group">
      <%= collection_select :course, :parent_id, @categories, :id, :name, { include_blank: true }%>
         <small>Leaving blank will create Category</small> 
    </div>
    <div class="form-group">
       <textarea type="textarea" id="course_description" name=course[description] class="form-control" id="description" aria-describedby="emailHelp" placeholder="Enter Desciption"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

app/views/courses/show.html.erb
<div class='container-fluid mt-4 courses'>
  <% if !@category_courses.blank? %>
    <% @category_courses.each do |course| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= course.name %></h5>
        <p class="card-text"><%= course.description %></p>
        <% if course.children.present? && course.parent.present? %>
          <%= link_to 'Available Courses', course, class: 'btn btn-outline-primary my-2 my-sm-0' %>
           <%#= link_to 'Enroll', enroll_path(course_id: course.id), class: 'btn btn-sm btn-success' , method: :post %>
           <%#= link_to 'Register', register_path(course_id: course.id), class: 'btn btn-sm btn-success' %>

        <% elsif current_user.enrollments.map(&:course_id).include?(course.id) %> 
          <button type="button" class="btn btn-secondary" disabled>Enrolled</button>
        <% else %>   
         <%= link_to 'Register', register_path(course_id: course.id), class: 'btn btn-sm btn-success' %></li>
        <% end %>
      </div>
    </div>
    <% end %>
  <% else %>
    <p>No Courses Available.</p>
  <% end %>

app/views/enrollments/index.html.erb
<div class='container-fluid mt-4 courses'>
  <% if !@user_courses.blank? %>
    <% @user_courses.each do |course| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= course.name %></h5>
        <p class="card-text"><%= course.description%></p>
      </div>
    </div>
    <% end %>
  <% else %>
    <p>No Courses Available.</p>
  <% end %>
</div>

app/views/enrollments/register.html.erb
<div class="container-fluid w-25 mt-5">
  <%= form_tag(enrollments_path, method: "post") do %>
  <div class="form-group">
      <input type="text" name="" class="form-control" id="course_name" value=<%= current_user.name %>> 
    </div>
    <div class="form-group">
      <input type="text" name="" class="form-control" id="course_name" value=<%= current_user.email %>> 
    </div>
    <div class="form-group">
      <input type="text" name="course_name" class="form-control" id="course_name" value=<%= @course.name %> readonly>
      <input type="hidden" name="course_id" value=<%= @course.id %> > 
    </div>
    <div class="form-group">
      <input type="text" class="form-control" id="course_category" value=<%= @course.parent.try(:name)%> readonly> 
    </div>
    <div class="form-group">
     <button type="submit" class="btn btn-primary float-right">Enroll</button>
    </div> 
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edcast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <%= link_to 'Edcast', courses_path, class: 'navbar-brand'%>
        </div>
      <div class="ml-1">
      <%= link_to 'Add Course', new_course_path, class: 'btn btn-outline-success my-2 my-sm-0' if can? :manage, Course %>
      <%= link_to 'My Courses', enrollments_path, class: 'btn btn-outline-primary my-2 my-sm-0' %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
      </div>
    </nav>
    <% end %>
    <% if flash[:notice] %>
      <div class="text-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="text-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>